### ---- Fig 1 e-f continued on from fig1.R ---- ###
## Generate average bigWig signal tracks for each histone mark ##
CHROM_SIZES="hg38.chrom.sizes"
OUTDIR="profile_outputs"

mkdir -p "${OUTDIR}"

make_avg_bw () {
    local outprefix="$1"
    shift
    local bws=("$@")
    local n=${#bws[@]}

    bigWigMerge "${bws[@]}" "${outprefix}.sum.bedGraph"

    awk -v n="${n}" 'BEGIN{OFS="\t"} {$4=$4/n; print}' \
        "${outprefix}.sum.bedGraph" > "${outprefix}.mean.bedGraph"

    sort -k1,1 -k2,2n \
        "${outprefix}.mean.bedGraph" > "${outprefix}.mean.sorted.bedGraph"

    bedGraphToBigWig \
        "${outprefix}.mean.sorted.bedGraph" \
        "${CHROM_SIZES}" \
        "${outprefix}.mean.bw"

    rm -f \
        "${outprefix}.sum.bedGraph" \
        "${outprefix}.mean.bedGraph" \
        "${outprefix}.mean.sorted.bedGraph"
}

# example usage : replace with bismark file paths
MARK="H3K4me3"

young_bws=(
    "YOUNG_SAMPLE_1_${MARK}_log2.bw"
    "YOUNG_SAMPLE_2_${MARK}_log2.bw"
    "YOUNG_SAMPLE_3_${MARK}_log2.bw"
)

old_bws=(
    "OLD_SAMPLE_1_${MARK}_log2.bw"
    "OLD_SAMPLE_2_${MARK}_log2.bw"
    "OLD_SAMPLE_3_${MARK}_log2.bw"
)

make_avg_bw "${OUTDIR}/young_${MARK}" "${young_bws[@]}"
make_avg_bw "${OUTDIR}/old_${MARK}" "${old_bws[@]}"

## deepTools Profile Plot Generation ##
# Requires BED files generated by fig1.R.
ml deepTools

run_profile () {
    local pathway="$1"
    local mark="$2"
    local region="$3"
    local bedfile="$4"
    local young_bw="$5"
    local old_bw="$6"
    local label="$7"

    computeMatrix reference-point \
        -S "${young_bw}" "${old_bw}" \
        -R "${bedfile}" \
        --referencePoint center \
        -b 5000 -a 5000 \
        --binSize 50 \
        --missingDataAsZero \
        --deepBlueURL "" \
        --samplesLabel Young Old \
        -out "${OUTDIR}/${pathway}_${mark}_${region}_matrix.gz"

    plotProfile \
        -m "${OUTDIR}/${pathway}_${mark}_${region}_matrix.gz" \
        --perGroup \
        --plotType lines \
        --averageType mean \
        --refPointLabel "center" \
        --regionsLabel "${label}" \
        --samplesLabel "Young" "Old" \
        --colors blue red \
        --plotWidth 10 \
        --plotHeight 10 \
        -out "${OUTDIR}/${pathway}_${mark}_${region}_plot.pdf"
}

# example usage : replace with mark and corresponding bed file (extracted with fig1.R)
MARK="H3K4me3"

run_profile \
    "GOBP_T_CELL_ACTIVATION" \
    "${MARK}" \
    "enhancers" \
    "H3K4me3_GOBP_T_CELL_ACTIVATION_enhancers.bed" \
    "${OUTDIR}/young_${MARK}.mean.bw" \
    "${OUTDIR}/old_${MARK}.mean.bw" \
    "T-cell activation enhancers"


